title: En Shao (邵 恩)
author: En Shao
logo: /2 inch-shaoen-gray.jpg
description: Institute of Computing Technology, Chinese Academy of Sciences 
google_analytics: 
timezone: UTC
theme: jekyll-theme-minimal
